### ISSUE TITLE
NER_using_Reformer(from examples): How do i predict my own data?

### ISSUE THREAD

**Issue by ricottablue** [SauravMaheshkar/Trax-Examples#1]
Hello Saurav,

I'm trying to predict my own data following the "NER_using_Reformer.ipynb" but i can't.

![image](https://user-images.githubusercontent.com/44533299/102368330-062d5300-3fbb-11eb-9c49-691046af21e1.png)

Can you explain me how do that?

I do not know if it is not implemented yet with reformer

Once I have trained the model, I cannot make predictions with new data.

Because 
Thanks.

**Comment by ricottablue** [comment]
i got an error with mode = 'predict'

![image](https://user-images.githubusercontent.com/44533299/102385985-ca9c8400-3fce-11eb-89ed-dd7d59ce08d8.png)

**Comment by SauravMaheshkar** [comment]
Hey, @ricottablue thanks for raising an issue ❤️ . 

I think the error is because `trax.models.reformer.Reformer` doesn't have a `mode = "predict"` mode. It just has train and eval. At least as per the latest documentation. You should use `trax.models.reformer.reformer.ReformerLM` because that has a `"predict"` option. 

Please try this and confirm if this works. If not, feel free to revert. 😃

**Comment by ricottablue** [comment]
sorry for the delay, i didn't see the answer till now,

Yes you are right (doesn't have that mode ) and i think you have to use the "trax.supervised.decoding.autoregressive_sample()", i think works, but i don't know why is so slow to make the prediction ahhahah and i don't know why

**Comment by SauravMaheshkar** [comment]
@ricottablue `autoregressive_sample()` uses recurrence for decoding embeddings into words, that's why it's so slow. Other decoding methods don't use the recurrence. It's like how LSTM's require a longer time to train than fully connected neural networks. 

I'm closing this issue for now. Feel free to open again if you have any more questions 😊.
